language: java

services:
  - docker

script:
  - bash docker_run.sh

env:
  global:
  - secure: PBIaXMsbFqaqi6e5WoFfjD00HCAHqisn6atQJP4+pF49oSl0ENeMSBIQqHP82AsK73QsMQ30AjWvzT3BN2D4+1kzF4oaby6mqCSMs6Nb2rD6jV82U0IX78aenDr8G+6xKUxqC161d4GsG4ozHoUzIAuLLd+ExSg0oaTdr/qCFh5x44DOdLhs3QroFshOFSmpjZ0gzjwgBr7w/y1KVDs3i8blRu+Wq90XHLNPLh3qgi5IwQpG2kX/MW76A+8pIUOW5/1pSuL+AvsDM7OLovvxpbjbJJrRiAGz/DY1pLDQMNYai2evhU9oeC4VbRerhdDvxEH3oVut1XbuP50DLkU6gZv+ZwQpfge1VGCGX0ftmTAQfITyHt74SOVhW2zLG8MXzLLHCpNo+RNyBh/61TbfpIUJ8+BSIkgL3Vu1Ggoi3bc6Gq7JM2SZ5cG6M8WHYT/OeSiSm5Yhi57+V6zoea1SoU0c/pte4QHY9EuKb38qCKMeMGXyfVXhu/ylx/HxzCf3T9nSG9KahLsHiJkXMkGJoUzO5Ux8hNZap63cNikQCi4IbJzHRnkkMX3xq8/FSgB2j5+5xHVDhIy11nqE4XfdfGZLaqQmgPJt76xXdRJPAi4jUUivxWLASXNsHQVUlVEbZDODdnNq2rkSUffaNx+N7C/OG5edie+t3V29poWpYZQ=
  - secure: UiqkALzg0pNUB4xR5/Mmg4l06dpSOgVojYZSZ/Pp5ZmELITZJoSW3kLtvGJX7RhcKwL5EELUG12h+XkjGEiGV8PPQsyQgRlbPV58GPsDpeGVgBhh3THFIdlWNod1peRmP2PJGGUZjoqDAMcEm27Zcg7q3TWR/pMxBiI/YFu50QWqgvFFgkjd/H8BfkI5cARVduc7E8//CwU9kOkdsvbF2CG2/BJ1jHa3nyPUttk7xf+Mz1Es2+nSKaW/i4YUe4/czHgwtFyt9gKOaOnYkNsiDcAjIbodrHmqKqLhnFxziOAZhrggVxfbAx96687XACBr6Qg6xjG0ypwPb+lr2m0uPVXhf/CZCGxJ1hRb0jLSaGaj7Tx57MOfTz0rsYHzjGyJ2rmS4G94fsIC769g4BeHdvdTATyrbTDXmNKAnqYYRJycCoHOU/8+rbXDJcBkNsgjFSsGXb9avT87IEQ/yYR0aXm+EGLAEzazlSmiIX7SuNonmArLBSEcgU7ip27xMa+FsnUwwfzqIXUUPVHpLJMbNMmTzB5A9XRdMFpFmCYwAW4sCuQCOP55sIgaHB7yWXVnNzBqn3WGBaM8PzmAJl/TJ07dZPe1w5QL5KEKHAGRfh1/BZc/pzwHePiaBDxBs/VwqjZA/56CeVwTYQVUoeL27CLhiywG6OWCOJfVBzliXkQ=
