language: java

# Details of the machine types on Travis to run the CI on
dist: xenial
os: linux

# The JDK we need for compiling
jdk:
  - openjdk11
services:
  - docker

script:
  - bash docker_push.sh

env:
  global:
  - secure: OiTB+uhABG9wdh86VmgmY/yyWJWoLtHUj7toOO+OHykBfrxP4u6ozS3ynYyYJ5PtGbBr6G3Y1q+UhiNJLm8kplpQJzQFBrxZ2msFqqBoZkHClKA9NrR+wPkWuuI+YTmWj7oPFMuk3hA0ktBQ8e2GrbVWhzHdOFiOWoxNNDF5wiXnQmNsj5OXSox9ilmnKnpvAj5pQiLYGisHe6gqcIGLOKfnTXZd+77thx3U9aCbeyV4O8Abw8W6G51bIsEFg8m3MML8vqU+M5K955K1h0T66SivVIN44Iydh/qS3vy29Xi5HtDN/Cps7CJ8yAkS7Ued5ms3wzARP79JIn3Q1CumwMAFCzoB5VXXHFGZW8NKh4KUmL/G3e7XjYW5ooXVQpTc4HqyHyDj4acS9T+u7VXl8F1BDG3KthQ2bx7YrYwLbFw5KyIgpVCICnCghYn8HMV+3TNAidjSxjQMr6eRt//phpfdS0X0rUwLMPgnRiGTJ8sfrrIUBr9O6qSsGV42a6e5L768Wsu3jEcA/nrPiRfDKEX1lgeQ9iLD4Yg8m1y0Drp92fUfLS9F3x9LYhHaOEIP2AYoyDZPB3dM+XOWkZYrJL2qHP+pglNf9xMmDxfyAi+jUO8IgEDoPrugin04wfjAbyY5pKf3RVMNpcu3GPgAhmE0qxDHPhuJKd0RXL6H+cA=
  - secure: NnbcTs1O4OIlIc3FN4Ill/annV9oAtuIMsJ0KMwnn0Opi6iXQhVfUByKTUMDAd4aKpaVXyAegLerpIVRAtuouDea7JX97TZutj66+LepmfZ6b9v68Lrxu8FtnuEQ2jyAWlrG3eqM3SPWPhUNxGX7DbF8V0UY5uWq5d0Ozv7pRTsI2hR/eI6sfGF1SJhnfgCzC6TN9u4qSTVEX5pNrBK+usbMbOFXvE0m8t/Fpi1yemlN+j5EFWE5eygM+RGhvWDgCrQJRxGKCrdQK9KyJaMlDOI5H57a4ZqhkFUoAHHD0OFx6D4wIzi893CDfD0/IBwBZHNyFi4VjH+3Zzrg/XYaknsQ/gnT59kVGVzEZS+EYjXcBHe7PeJ0mfHSK6wS3gjFJmS0fLHxT1cqIbbt+pwi/cDHwr0Cdcv0bHJU5wduJBQOV6vTxWZbnxTb5bB+SFX19GwGnHiADpxBrUn/KJ6o9be8qCxU5T4++M7o43XfKyeI6E07kRsThNf2aF32jUYpPv+5cMUnulk7YTtJpgq6gBO8FjrWJdC971+PwCrH38ln7Si4lZXCG0QB0iA0jHOemSOIivO9D/JnK8aTaCdsdT9EqtSExsGK9GouJHls1nlKCKQWhh2hUWpQ9l1s13xM0yNzIXaS5S6jfSwMnAsQNkF/RW32EbhX1fTlvOZsODs=
