language: java
services:
- docker

env:
  global:
    - GCP_PROJECT_ID=devops05-290206
    - IMAGE=gcr.io/devops05-290206/docker
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_98d237b7dbf4_key -iv $encrypted_98d237b7dbf4_iv -in google-key.json.enc -out google-key.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source "$HOME/google-cloud-sdk/path.bash.inc"
  - gcloud auth activate-service-account --key-file=google-key.json
  - gcloud auth configure-docker
  - gcloud config set project "${GCP_PROJECT_ID}"

install: true # no-op



script:
  - |-
    set -ex;
    docker build -t "${IMAGE}:${TRAVIS_COMMIT}" . && \
    docker push "${IMAGE}:${TRAVIS_COMMIT}" && \
    set +x
