language: java

services:
  - docker

script:
  - bash docker_push.sh

env:
  global:
  - secure: R9BLUuBF6D3FLzRr0U/rbOAb315sqQMPyNLNZBNjNZ2ef63K+NV4C32M8f70PS3g7baBWvJ7cpZqDNSpx7lzcT+IrW+Z0wVAMt8oASJRSCcywsqk6ZnpNpM9bSK8d3RKSuwQZDVRHABAtNKfgpDhpib8gKv1t3Vnq9OPGF+DGWH/m9yGqlUQNMBrz9AvUrUY3S+TNUIP76S9Vqhx8rvNucA9V9JML83JIvz47apGj8tVdomlJ8NkzjvanxiY3LlogdUmNiQJnRKoFW0cbH8+ON7fzjTc7i8gl2EzDcTmk5Greokh8LEK7RVSbNJKWgjL2M68p+UwfqbyRnl2wsDmmwKU5duhGWkZO/JjT+HnHJuJgUVOzcZ0utPuotsbd57IYfhtJ8/R9zaUIe66Ce9kgfTM74KejFjvYTajSR1iQRPvE2QAqj7w9zzcuwSPwGp722d6c9Uaj4+C4DCupZfAG1dpW9MZbqE86UE97iFM+apzY5g8oN81OJott09Qufgd9o8X7x4ylNeVV67aaW2GuWJ/VeXESe+UZ6iFsLjafJfQ3FBuJNc7rDcUVME3kPcWdjy5jpRvK7uKLArzM5ZGVKN03SBjK8ItS9+xozg72RpJW1qVK60ue6sCqrDzdi+lGG/quVhKiDv2AO4TRHjSU794+5CqEgzz7UQveIEk1/0=
  - secure: QNtdWSCFRn4jesf9fY3ErG9xmOnwwZsUNCZZsEZIjN9vKgNKA3UtH4RPTH4qd3PbCNm9s8Kw26nlRsFqFYNHL6z/n92Cc8Uzf6bEa5Mwgfw6xD3lHzKcSK9dUaYAkiXKWeejExYJDjde1N366TBQmtwGtlfazKUWxmF00ut9M2c4VF6dOiJ8sK9HaJm5jxPqhiLeK0IQitYdQ0zVjBRsiPpoxj84wSsSoS0zQqa02YQiAQzc93/yDpiM/kINYxv/oAvBwbVojBqi0wUVcegYcVy3UyDWRTIU5w60ajxc3onFNMmOLYpKvJD9hlQXYX3RdcSj/ZnpL+eb1qu1mU7yQiwnrRcAk6mofyyQXzaLWyQ3tPWfcWLh6DyaBX2kOvf8wBDVEGrroccnsyOphjLKotuUdRpDzccAw5ZS1Rbe1doKMnrS7V6zrR1Y/xe+WpmT+mc8f3flWcujmU4tmuE1+GzfsdGDW6wk3nFccG8d+usDlrXhYKJs2cbVJ27I1liEUOobeCqKpsUWKmEFCAgjtOyZbNMdPiFAePf/sa0Luhd1XgeLv65maIzoFFAeGvN4BRSfyK8z5lM7pbQ77nvNlifD0uUeYcfj0RA5/1Y4dSeOf/NUOJ0OsXyrCNLgebB5bCOnqwldhdjMr5Zr/IclnjzCmorMg4u7/WnNeMPUYBc=
